# -*- coding: utf-8 -*-
"""Spam_email_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MW8g_KNQsxULc5a0_Zhnx7TTEaUzRMF0
"""

!pip install streamlit scikit-learn pandas pyngrok

#import necessary libraries
import pandas as pd
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

# Load dataset
file_path = "/content/spam (1).csv"
data = pd.read_csv(file_path, encoding='latin-1')
data.head()

# Keep relevant columns
data = data[['v1', 'v2']]
data.columns = ['label', 'message']

# Convert labels to numerical values
data['label'] = data['label'].map({'ham': 0, 'spam': 1})

# Split data
X_train, X_test, y_train, y_test = train_test_split(data['message'], data['label'], test_size=0.2, random_state=42)

# Create a pipeline (TF-IDF Vectorizer + Naïve Bayes Model)
model = Pipeline([
    ('tfidf', TfidfVectorizer(stop_words='english')),
    ('classifier', MultinomialNB())
])

# Train the model
model.fit(X_train, y_train)

# Save the trained model
pickle.dump(model, open("spam_model.pkl", "wb"))

print("✅ Model training complete and saved as 'spam_model.pkl'")

"""**Create a streamlit app**"""

with open("app.py", "w") as f:
    f.write("""
import streamlit as st
import pickle

st.title("Spam Detector using Naïve Bayes")
st.write("Enter a message below to check if it's spam or not.")

# Load the trained model
loaded_model = pickle.load(open("spam_model.pkl", "rb"))

# User input
message = st.text_area("Enter your message:")

if st.button("Check"):
    if message.strip():
        # Make prediction
        prediction = loaded_model.predict([message])[0]

        # Display result
        if prediction == 1:
            st.error("🚨 This message is SPAM!")
        else:
            st.success("✅ This message is NOT spam.")
    else:
        st.warning("Please enter a message to check.")
""")

